### ISSUE TITLE
If deposits are ordered by author, they are ordered by first name

### ISSUE THREAD

**Issue by terrainsvagues** [mlaa/humcore#1]
This isn't intuitive and is likely to confuse users. Switch to ordering by last name.

**Comment by chriszarate** [comment]
Considering the problematic construct of first/last name, can we also consider removing the author sort facet and pushing users towards the (very good) search?

**Comment by rekmla** [comment]
It's possible to modify the author_sort field to contain "last name, first name". However, the field contains multiple names when more than one author is entered for a deposit. We are removing the primary author designation ( see issue #2 ).

It would be better to remove the author sort. It does not add that much value to the search and display.

**Comment by terrainsvagues** [comment]
Let's remove author sort then. Fine by me.

**Comment by rekmla** [comment]
Author sort removed.
