### ISSUE TITLE
Attribution Text and Images for CORE

### ISSUE THREAD

**Issue by terrainsvagues** [mlaa/humcore#11]
CORE is the result of a collaboration between the [Modern Language Association] (http://mla.org) and the [Center for Digital Research and Scholarship] (http://cdrs.columbia.edu/) at Columbia University. Development was funded in part by a generous [Digital Humanities Start-Up Grant] (http://www.neh.gov/grants/odh/digital-humanities-start-grants) from the [National Endowment for the Humanities] (http://www.neh.gov/). 

![neh_logo_horizlarge](https://cloud.githubusercontent.com/assets/7083891/9498672/f7fb6d9c-4be8-11e5-8490-f003d3d8548e.jpg)
![mla_logo](https://cloud.githubusercontent.com/assets/7083891/9499205/f347e32c-4beb-11e5-8e76-96b16811ab3d.jpg)

Note: awaiting fancy logo from Mark for CDRS

**Comment by rekmla** [comment]
Where on the site will this be placed?

**Comment by rekmla** [comment]
Widget deployed.
