### ISSUE TITLE
Non-array in META tag authors loop

### ISSUE THREAD

**Issue by chriszarate** [mlaa/humcore#18]
This occasionally pops up in the logs:

`PHP Warning:  Invalid argument supplied for foreach() in .../plugins/humcore/functions.php on line 197`

https://github.com/mlaa/humcore/blob/master/functions.php#L197

I haven't been able to narrow it down to a specific deposit. All deposits seem to have authors. It'd be easy enough to sidestep with a type check, but I'd rather figure out what is causing a non-array value here.

**Comment by chriszarate** [comment]
Wait, found some URLs in the logs.

`/deposits/item/mla:97/`
`/deposits/item/mla:155/`
`/deposits/item/mla:151/`

Are they getting dropped?

**Comment by rekmla** [comment]
These examples are deposits that had been manually purged (duplicates). Since these urls bring up a blank page. We should probably add a not found message and exit early.

**Comment by chriszarate** [comment]
Ah, cool. The BuddyPress way (which I'm not a huge fan of) is usually to return `302` and dump users back to the home page. We can do that for now. If we return `404` we'd need to write and serve up an error page.

**Comment by chriszarate** [comment]
Or probably directing them to `/deposits/` is better.

**Comment by chriszarate** [comment]
[Deleted previous comments written before coffee.] Yes, let's exit early and `404`.
