### ISSUE TITLE
Allow whitelisted groups to deposit as groups

### ISSUE THREAD

**Issue by terrainsvagues** [mlaa/humcore#19]
If an MLA member is a member of a whitelisted group, he or she may deposit to CORE on behalf of that group.
Example: Member of MLA committee
Example: Editor of MLA publication
Example: MLA member also member of allied organization

**Comment by rekmla** [comment]
1. What are the whitelisted groups? Is it all Committees (group type M), or a subset?

2. Assuming we want an additional conditional pick list on the deposit page that shows only the committees a user has access to.

3. Are these deposits public and faceted on the search results page?

**Comment by kfitz** [comment]
These are good questions!

1. I would suggest that we start somewhat narrowly -- so perhaps make it committees only, at first, and see whether there is interest in other quarters (and whether we want to support that interest).

2. I think so, yes. So perhaps a question like "Are you depositing on behalf of an MLA committee?" and, if the answer is yes, a pick list of the appropriate committees?

3. I'd say yes.

**Comment by rekmla** [comment]
Members who are members of Committees (group type M) now have the ability to deposit on behalf of the Committee. The Committee will be the author of the deposit, not the member. The Fedora and Solr metadata, deposits list page, deposit detail page, group deposit page, member deposit page and activity records will all show the committee as author if that option was selected at time of deposit. Members that are not members of a committee will not see this choice.

Other changes implemented to support this include a deposit review page that is displayed upon deposit, restricting the total views and downloads counters to exclude self views and the removal of the primary author flag. Authors will now be listed by last name.

Minor changes added to this commit include removal of new_group_deposits activity records from the everything activity filter and addition of a Poetry item type.

We will need to do some more testing before deployment, add additional text to the deposit review and have an editorial review.

**Comment by rekmla** [comment]
Complete, implementation on hold.
