### ISSUE TITLE
Provide deposits rss feed.

### ISSUE THREAD

**Issue by rekmla** [mlaa/humcore#50]

**Comment by terrainsvagues** [comment]
This is to help with Google Scholar situation?

**Comment by rekmla** [comment]
No, I believe you requested this to possibly supply a widget.

**Comment by terrainsvagues** [comment]
As a super admin, I can create a widget featuring the latest items uploaded to _CORE_.

Use case: To enable the featuring of _CORE_ deposits (faceted / latest) on the home page of the _Commons_ and elsewhere.
