### ISSUE TITLE
Member uploaded wrong thing

### ISSUE THREAD

**Issue by terrainsvagues** [mlaa/humcore#51]
Member uploaded entire journal issue instead of article to /mla453
[ECI_March 2011.pdf](https://github.com/mlaa/humcore/files/86473/ECI_March.2011.pdf)

Article attached. Having the whole issue up there probably means we're breaching copyright...

**Comment by terrainsvagues** [comment]
[ECI_March 2011.pdf](https://github.com/mlaa/humcore/files/86471/ECI_March.2011.pdf)

**Comment by rekmla** [comment]
Additional file updates needed:
mla:295
mla:519
mla:525

**Comment by rekmla** [comment]
Completed.
