### ISSUE TITLE
Facet sidebar is covering item description

### ISSUE THREAD

**Issue by terrainsvagues** [mlaa/humcore#6]
On item detail page of http://dx.doi.org/10.17613/M6QC73 and http://dx.doi.org/10.17613/M6V30X (duplicate deposits) ![screen shot 2015-08-24 at 9 34 53 am](https://cloud.githubusercontent.com/assets/7083891/9441454/2c0b166a-4a44-11e5-919c-5ef0067f3165.png)

**Comment by rekmla** [comment]
Duplicate deleted. I believe this was caused by hitting the Deposit button twice. Format problem is caused by the extra long url in the note. Will look at the css rules.

**Comment by rekmla** [comment]
Deployed.
