### ISSUE TITLE
Cannot edit metadata after deposit

### ISSUE THREAD

**Issue by terrainsvagues** [mlaa/humcore#61]
User Story: After depositing to CORE, I have no way of going back into metadata to alter information about my deposit.

**Comment by chriszarate** [comment]
Questions for discussion:

1. Is there a finite time window during which edits can be made?

2. What fields are editable and not editable?

3. Are edits subject to approval/reversal?

4. Do we need a policy statement governing this feature?

5. How are changes recorded? Are they surfaced to the user and, if so, how?

**Comment by chriszarate** [comment]
Provisional answers:

1. Time limit of 24 hours to allow user's to edit metadata of their own deposit. After that time period, the edit link will lead to a contact information for Commons staff.

2. All metadata fields excepting group association are editable. The deposited object is not editable or replaceable.

3. No, although we will continue to communicate with depositors if we notice something that may need correction or addition.

4. Yes.

5. We should add "Date deposited" and "Date last updated" to the deposit page.
