### ISSUE TITLE
Add language of deposit to required metadata

### ISSUE THREAD

**Issue by terrainsvagues** [mlaa/humcore#66]
Default to English, but allow users to choose from picklist of other MLA languages.

**Comment by rekmla** [comment]
Attached list of languages provided by Chris. Seems too extensive for our purposes.

[lang.txt](https://github.com/mlaa/humcore/files/180129/lang.txt)

**Comment by rekmla** [comment]
@terrainsvagues, any comment on the attached language list?

**Comment by rekmla** [comment]
This item was completed.
