### ISSUE TITLE
No published item type for monograph / book

### ISSUE THREAD

**Issue by terrainsvagues** [mlaa/humcore#86]
We currently don't allow users to select monograph or book as a 'previously published?' item type. Let's fix that.

**Comment by rekmla** [comment]
1. Do we want to also add monograph as an item type?
2. Here are the types known to the Crossref API:

- 			{"id":"book-section","label":"Book Section"},
- 			{"id":"monograph","label":"Monograph"},
- 			{"id":"report","label":"Report"},
- 			{"id":"book-track","label":"Book Track"},
- 			{"id":"journal-article","label":null},
- 			{"id":"book-part","label":"Part"},
- 			{"id":"other","label":"Other"},
- 			{"id":"book","label":"Book"},
- 			{"id":"journal-volume","label":"Journal Volume"},
- 			{"id":"book-set","label":"Book Set"},
- 			{"id":"reference-entry","label":"Reference Entry"},
- 			{"id":"proceedings-article","label":"Proceedings Article"},
- 			{"id":"journal","label":"Journal"},
- 			{"id":"component","label":"Component"},
- 			{"id":"book-chapter","label":"Book Chapter"},
- 			{"id":"report-series","label":"Report Series"},
- 			{"id":"proceedings","label":"Proceedings"},
- 			{"id":"standard","label":"Standard"},
- 			{"id":"reference-book","label":"Reference Book"},
- 			{"id":"journal-issue","label":"Journal Issue"},
- 			{"id":"dissertation","label":"Dissertation"},
- 			{"id":"dataset","label":"Dataset"},
- 			{"id":"book-series","label":"Book Series"},
- 			{"id":"edited-book","label":"Edited Book"},
- 			{"id":"standard-series","label":"Standard Series"}

**Comment by rekmla** [comment]
This item was completed.
